### ISSUE TITLE
Suggest to add a feature to skip the html flags

### ISSUE THREAD

**Issue by anysql** [lionsoul2014/friso#1]
Currently friso will interpret the html flags, hope it can be skiped.

friso>> <html>中国</html>
分词结果:
html 中国 html
Done, cost < 0.000000sec

It should just return 中国

**Comment by lionsoul2014** [comment]
In a web application, of course you want friso to skip the html flag for you!

In my opinion friso should never do any elements skip, it should not affect the original source stream, it just focus on the "Segmentation" and cut whatever you give it to!

If you want filter some elements, like the html flag, you should filter it before you invoke the friso_set_text or friso_next.

Thanks for your suggestion!

**Comment by lionsoul2014** [comment]
It will be a good advice to implemented this as an optional plugin of friso!
