### ISSUE TITLE
注释中的word poll

### ISSUE THREAD

**Issue by MouseZhangZh** [lionsoul2014/friso#15]
`friso.c`中`next_mmseg_token`和`next_detect_token`的注释中有几个`word poll`，是否是拼写错误呢？我猜是`word pool`，不知道对不对.:bug::bug::bug:

**Comment by lionsoul2014** [comment]
感谢指正，拼写错误，会在后续版本纠正。

**Comment by lionsoul2014** [comment]
已经更新
