### ISSUE TITLE
字典自訂詞庫

### ISSUE THREAD

**Issue by ricoisme** [lionsoul2014/friso#18]
hi
我使用RediSearch並透過字典設定相關自訂詞庫，但查詢相關自訂詞彙都找不到結果，
我是否有忽略什麼設定?
謝謝

**Comment by lionsoul2014** [comment]
加入词条，重启服务就可以生效，注意编码版本和实际使用的词库路径。

**Comment by ricoisme** [comment]
先感謝回覆，檔案編碼為UTF8，加入詞條後也有重啟RediSearch，但透過NRediSearch查詢還是找不到相關自訂詞條(糖水)，可能是Client driver沒有支援同義詞查詢，我在確認看看，謝瞜

我自訂詞條內容如下
可口可乐/糖水,可乐
可口可樂/糖水,可樂

**Comment by lionsoul2014** [comment]
应该是没支持的，他们这块的支持还相对比较若。https://github.com/RediSearch/RediSearch/issues/1084

**Comment by ricoisme** [comment]
got it and thanks
