### ISSUE TITLE
添加中文转拼音  例如 中国 -> zhongguo, 通过 zhongguo能够搜索到中国这个词条

### ISSUE THREAD

**Issue by apl0219** [lionsoul2014/friso#19]
添加中文转拼音  例如 中国 -> zhongguo, 通过 zhongguo能够搜索到中国这个词条，

**Comment by lionsoul2014** [comment]
这个本身就支持，如果不想要，直接去掉拼音追加就好。
https://search.gitee.com/?skin=rec&type=repository&q=fenci
