### ISSUE TITLE
msys2 + Mingw编译不成功

### ISSUE THREAD

**Issue by retsyo** [lionsoul2014/friso#2]
$ make
gcc -O2 -Wall -fPIC -c friso.c -lm
gcc -O2 -Wall -fPIC -c friso_array.c
gcc -O2 -Wall -fPIC -c friso_hash.c
gcc -O2 -Wall -fPIC -c friso_lexicon.c
friso_lexicon.c:253:24: warning: 'indexOf' defined but not used [-Wunused-function]
 __STATIC_API__ fstring indexOf( fstring __str, char delimiter )
                        ^~~~~~~
gcc -O2 -Wall -fPIC -c friso_link.c
gcc -O2 -Wall -fPIC -c friso_string.c
gcc -O2 -Wall -fPIC -c friso_ctype.c
gcc -O2 -Wall -fPIC -c friso_UTF8.c
gcc -O2 -Wall -fPIC -c friso_GBK.c
gcc -O2 -Wall -fPIC friso.o friso_array.o friso_hash.o friso_lexicon.o friso_link.o friso_string.o friso_ctype.o friso_UTF8.o friso_GBK.o -fPIC -shared -lm -o libfriso.so
gcc -O2 -Wall -fPIC -c tst-friso.c
gcc tst-friso.o -o ./friso -L. -lfriso
E:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.2.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lfriso
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:41: friso] Error 1

**Comment by lionsoul2014** [comment]
cygwin编译，使用Makefile.cygwin这个Makefile，重命名下！
原因是：-lfriso 找不到friso.so文件报错！

**Comment by retsyo** [comment]
把Makefile.cygwin里面所有的--mno-cygwin删除，可以编译了

$ make -f Makefile.cygwin
gcc -O2 -Wall -shared friso.c friso_array.c friso_hash.c friso_lexicon.c friso_link.c friso_string.c friso_ctype.c friso_UTF8.c friso_GBK.c  -o friso.dll -Wl,--output-def,friso.def,--out-implib,friso.lib
friso_lexicon.c:253:24: warning: 'indexOf' defined but not used [-Wunused-function]
 __STATIC_API__ fstring indexOf( fstring __str, char delimiter )
                        ^~~~~~~
gcc tst-friso.o -o ./friso -L. -lfriso

**Comment by lionsoul2014** [comment]
好的！
