### ISSUE TITLE
win7 dos窗口，乱码

### ISSUE THREAD

**Issue by retsyo** [lionsoul2014/friso#3]
已经修改friso.ini的
> friso.charset = 1
> friso.lex_dir = ./vendors/dict/GBK/

R:\friso\src>friso.exe -init ..\friso.ini
Initialized in 0.260000sec
Mode: Complex
+-Version: 1.6.2 (GBK)
+-----------------------------------------------------------+
| friso - a chinese word segmentation writen by c.          |
| bug report email - chenxin619315@gmail.com.               |
| or: visit http://code.google.com/p/friso.                 |
|     java edition for http://code.google.com/p/jcseg       |
| type 'quit' to exit the program.                          |
+-----------------------------------------------------------+
friso>> 研究生命起源, i love c++.
鍒嗚瘝缁撴灉:
研究 琢磨 研讨 钻研 生命 起源 , i love c++ .
Done, cost < 0.000000sec

**Comment by lionsoul2014** [comment]
GBK编码的中文已经正确切分了，这个没有问题。

friso>> 研究生命起源, i love c++.
鍒嗚瘝缁撴灉:

这个的乱码是因为friso的tst-friso.c的源码的是utf-8编码的，里面有中文，而windows的cmd是GBK编码的，所以显示乱码！

你直接选择和你的项目一样的编码使用是不会有任何编码问题，你也可以更改tst-friso.c测试，使用GBK编码打开，然后更改下里面的乱码的中文，再编译安装下，运行测试程序就不会看到这个乱码了。
