### ISSUE TITLE
请支持一下 PHP7

### ISSUE THREAD

**Issue by solicomo** [lionsoul2014/friso#4]
PHP 扩展在 PHP7 下编译不过。

能否考虑支持 PHP7 一下？

多谢了。

**Comment by lionsoul2014** [comment]
已经在计划中了，会在下一个版本一起发布，感谢关注，这个因为时间问题拖了很久了！

**Comment by dongyado** [comment]
已经上线php7 版本，可以帮忙测试一下

**Comment by Yahasana** [comment]
编译.so和.dll扩展方便人家帮你测用啊，要帮助开发者走完最后一步，不然每个人想用你的东西都要自己折腾编译一番？
