### ISSUE TITLE
支持android吗

### ISSUE THREAD

**Issue by zxfzqf** [lionsoul2014/friso#5]
有看到friso是跨平台的，所以想在安卓中使用，使用jni方式直接加入源码，好像不能使用，一直出现未定义的引用错误，刚接触android , 所以不知道是我使用方式不对，还是 friso暂时不能跨平台到android, friso支持安卓吗？麻烦了。

**Comment by lionsoul2014** [comment]
可以把你的错误信息贴出来看下，这个错误一般是没有成功加载friso.so文件，只要支持ANSI C就可以，和平台无关！
具体，对Android也不熟悉，Java的可以使用java版本：https://github.com/lionsoul2014/jcseg

**Comment by zxfzqf** [comment]
@lionsoul2014 谢谢！找到原因了， 还是对jni不够熟悉的原因啊，jni机制下，c++接口函数必须是以C的方式导出 ，friso_API.h中 宏：

#define FRISO_API extern
改为 
#ifdef  __cplusplus
#define FRISO_API extern "C"
#else
#define FRISO_API extern
#endif

就可以了。
谢谢作者，thx。

**Comment by lionsoul2014** [comment]
OK，棒棒的！
