### ISSUE TITLE
麻烦支持下php7.0

### ISSUE THREAD

**Issue by xiejunyu** [lionsoul2014/friso#7]
麻烦支持下php7.0,用过结巴 SCWS 还是觉得friso分词好.

**Comment by jason-2026-x** [comment]
php7.0 
php7.0

**Comment by lionsoul2014** [comment]
哈哈，这个问题被提到好多次了，现在确实时间上比较挤。纳入计划了，如果熟悉java可以使用friso的java版本jcseg，功能更全些，提供直接的http调用！

**Comment by dongyado** [comment]
@xiejunyu  php7 扩展已经上线 麻烦编译测试一下 有问题及时反馈 暂时只支持 linux
