### ISSUE TITLE
undefined symbol: friso_new

### ISSUE THREAD

**Issue by hepking** [lionsoul2014/friso#8]
php 扩展在重新启动的时候报错， centos7.3x64  lnmp1.3  friso-1.6.2-release

**Comment by hepking** [comment]
PHP Version 5.4.45

**Comment by lionsoul2014** [comment]
安装配置问题，参考下，http://blog.aboutc.net/php/59/php-installation-robbe-chinese-word-extension
里面提到的robbe就是php扩展，后来合并到一起了

**Comment by hepking** [comment]
能不能打个个正确版本的，还有及时的文档呢？还得到处找资料，另外有没有最新的词库，这个词库不仅少，而且有点过时

**Comment by lionsoul2014** [comment]
有的资料都在：http://git.oschina.net/lionsoul/friso
欢迎贡献词库。。。

**Comment by hepking** [comment]
friso.lo: /root/friso-1.6.2-release/vendors/binding/php/friso.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/friso-1.6.2-release/vendors/binding/php $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/friso-1.6.2-release/vendors/binding/php/friso.c -lfriso -o friso.lo 
$(phplibdir)/friso.la: ./friso.la
	$(LIBTOOL) --mode=install cp ./friso.la $(phplibdir)

./friso.la: $(shared_objects_friso) $(FRISO_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -lfriso -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_friso) $(FRISO_SHARED_LIBADD)


改了还是不行呢
