### ISSUE TITLE
Parse configuration from string

### ISSUE THREAD

**Issue by mnunberg** [lionsoul2014/friso#9]
It would be nice if friso could parse its configuration and load its dictionaries etc. from a string in memory rather than doing filesystem access directly. This would allow us to embed the dictionaries and configuration within the application itself rather than having to ship it alongside it (or manually hard-code defaults).

I can implement this feature if you'd like me to.

**Comment by lionsoul2014** [comment]
In a real application environment we use to put the lexicon files out of the application, in that way we could easily modify the lexicon file whenever you want without re-compile or repackage the application.

That will be nice if u would like to spend some time to finish the implementation u describled
U could add a new function named "friso_init_from_string" or whatever and implement your logic inside.
